In [8]:
print("Hello world")

Hello world


# Numpy
np.array -> bikin list jadi array
np.diag -> nilai diagonalnya
np.abs -> nilai absolute
np.fill_diagonal -> ngisi nillai diagonal jadi value yang kira mau
np.sum -> ngejumlahin semuanya
np.all -> melakukan test di semua nilai
np.zeros -> ngebikin array (np.array) yang isinya 0
np.dot -> melakukan perkalian matrix
np.sqrt -> akar 

In [9]:
# Import Numpy
import numpy as np

# cek diagonally dominant
def IsDiagonallyDominant(x):
    x = np.array(x) # ubah jadi array

    diag = np.diag(np.abs(x)) # ambil nilai diagonal absolute

    # axis 1 = jumlahin baris
    # axis 0 = jumlahin kolom
    off_diag = np.sum(np.abs(x), axis = 1) - diag # nilai off diagonal

    # cek diagonally dominant
    if np.all(diag > off_diag):
        return True
    else:
        return False

# gaus seidel
def GaussSeidel(x,y, epsilon = 0.01, t = 15):
    # check diagonally dominant
    if not IsDiagonallyDominant(x):
        print("Not Diagonally Dominant")
        return
    
    # ubah jadi array
    x = np.array(x)
    y = np.array(y)

    # ambil nilai diagonal, nanti bakal dipake buat ngebagi
    diag = np.diag(x)

    # Negasi semua nilai
    x = -x

    # ngilangin diagonal
    np.fill_diagonal(x,0)

    # inisialisasi nilai awal
    # x[0] -> karena ukuran dari matriz pasti sesuai sama ukuran 1 baris
    # di bilai x
    mtx_old = np.zeros(x[0].shape)

    # mulai iterasi gaus seidel
    for i in range(t):
        # bikin mtx new dengan ngebuat array dari mtx old
        mtx_new = np.array(mtx_old)

        # bikin iterasi buat masing masing vaeiable
        for idx, row in enumerate(x):
            mtx_new[idx] = (y[idx] + np.dot(row, mtx_new)) / diag[idx] 
        
        # print hasil iterasi
        print (f"iterasi ke-{i}")
        print(mtx_new)

        # cek nilai epsilon
        dx = np.sqrt(np.dot(mtx_new - mtx_old, mtx_new - mtx_old))
        print(f"dx: {dx}")

        if dx < epsilon:
            print("converged")
            return
        
        mtx_old = mtx_new

    print("Not Converged")
    return


In [10]:
Xs = [
    [10,4,5],
    [1,6,1],
    [3,1,6],
]

Ys = [8,5,10]

GaussSeidel(Xs, Ys)

iterasi ke-0
[0.8  0.7  1.15]
dx: 1.5660459763365826
iterasi ke-1
[-0.055       0.65083333  1.58569444]
dx: 0.9608704439365717
iterasi ke-2
[-0.25318056  0.61124769  1.69138233]
dx: 0.22806245930668492
iterasi ke-3
[-0.29019024  0.59980132  1.7117949 ]
dx: 0.04378822902864041
iterasi ke-4
[-0.29581798  0.59733718  1.71501946]
dx: 0.006938385517329205
converged
